Gabriel/op 177 UI to view the events created from a given address
bleu/op-bacchus pull request #10
Opened 2024-09-04 15:43 UTC by gabrielorleans

<img width="1168" alt="Screen Shot 2024-09-04 at 12 42 11" src="https://github.com/user-attachments/assets/c35d5173-6f30-41fc-afad-e0babd0f6549">

home page developed with:

- grid with events list;
- search bar;
- title.

2024-09-04 17:10 UTC, ribeirojose commented on package-lock.json
what's with the package-lock, guys? 😅

2024-09-05 13:02 UTC, luizakp commented
this PR needs a rebase against `main`

2024-09-05 13:02 UTC, luizakp commented on package-lock.json
please use only one package manager. Or npm or yarn

2024-09-05 13:14 UTC, luizakp commented on src/app/home/page.tsx
> +        [1, 2, 3, 4, 5, 6].map((event) => (
we should use the schema structure. Please view https://github.com/bleu/op-bacchus/pull/6/files#r1745515431 or https://github.com/bleu/op-bacchus/pull/8/files#r1745517704

2024-09-05 13:15 UTC, luizakp commented on src/app/home/page.tsx
> +        <div className="grid grid-cols-3 gap-12 mt-10">
think this is breaking on mobile hehehhehe

2024-09-05 13:15 UTC, luizakp commented on src/components/Header.tsx
>  export function Header() {
probably breaking on mobile too

2024-09-05 13:17 UTC, luizakp requested changes
please rebase and fix the package situation before merging it. Happy to see you first PR ;)

2024-09-05 14:46 UTC, merged