Gabriel/op 243 ticket schema and attestation
bleu/op-bacchus pull request #18
Opened 2024-09-11 14:14 UTC by gabrielorleans

<img width="1470" alt="Screen Shot 2024-09-11 at 11 13 01" src="https://github.com/user-attachments/assets/55e97b02-5fe1-471c-b5d0-8492f859f989">

Needs to be placed in the right page in future steps.

Already checked on etherscan https://sepolia-optimism.etherscan.io/tx/0x6417a30244895e8aabe2c7013a4313029f3f94027a02fb7777440fefa0843fdd

2024-09-11 14:58 UTC, luizakp commented on src/components/CreateTicketSchemaButton.tsx
> +// import { CREATE_EVENT_SCHEMA } from "./CreateEventSchemaButton";
please remove comments and console logs

2024-09-11 14:58 UTC, luizakp commented on src/components/CreateTicketSchemaButton.tsx
> +  console.log(CREATE_TICKET_SCHEMA_UID)
https://github.com/bleu/op-bacchus/pull/18/files#r1754856580

2024-09-11 15:00 UTC, luizakp commented on src/app/page.tsx
> +      <CreateTicketAttestationButton />
this can be added on the` /admin` if you rebase with main

2024-09-11 15:02 UTC, luizakp commented on src/components/CreateTicketAttestationButton.tsx
> +} as Ticket;
appreciate this being a start and a ticket is really being created! but with the current state of the project, you can already create a ticket linked to a real event and with the current connected wallet address

2024-09-11 15:03 UTC, luizakp commented on src/components/CreateTicketAttestationButton.tsx
> +  }
🔝

2024-09-12 11:12 UTC, JeanNeiverth requested changes
It would be better if you rebase / merge main before the PR, this way (i) you will be able to put the buttons in /admin page and (ii) the reviewers will know all the changes being being proposed considering the current main, not the old one

2024-09-13 15:26 UTC, merged