Add search bar and filter by date for real events in home page
bleu/op-bacchus pull request #22
Opened 2024-09-13 18:50 UTC by gabrielorleans

<img width="1419" alt="image" src="https://github.com/user-attachments/assets/5198ff6d-8534-4aed-936b-1c79195b2c03">

Search bar now functional and displaying only (1) events published and (2) yet to happen

2024-09-13 19:06 UTC, luizakp commented on yarn.lock
👀

2024-09-16 14:56 UTC, luizakp requested changes
This is not getting all events

2024-09-16 15:11 UTC, luizakp commented on src/app/page.tsx
>  		query: USER_ATTESTATIONS_QUERY,
this is the wrong Query... we talked about it on the daily. You should get all the events, so all the attestations that has the same schema ID

2024-09-16 15:13 UTC, luizakp commented on src/app/page.tsx
> +					className="w-full h-32"
why this card is different from the one on events page?

2024-09-16 15:13 UTC, luizakp commented on src/app/page.tsx
> +					className="w-full h-32"
home page AttestationItem

```

function AttestationItem({ data }: { data: any }) {
	const parsedData = parseEventsData(data);

	return (
		<div
			key="Event"
			className="border-2 rounded-lg w-[80vw] sm:w-[70vw] md:w-[50vw] lg:w-[25vw] h-auto gap-6 justify-self-center"
			>
			<div className="p-3">
				<h2 className="text-base font-bold">{parsedData.name}</h2>
				<p className="text-xs">{epochToCustomDate(parsedData.startsAt)}</p>
			</div>
			<div>
				<img
					className="w-full h-32"
					alt="Template image"
					src={parsedData.imageUrl}
				/>
			</div>
			<div className="p-3">
				<p className="text-xs text-gray-700 mb-4">
					Brief description: {parsedData.briefDescription}
				</p>
				<span className="text-xs bg-gray-100 px-2 py-1 rounded-lg inline-block">
					Status: published
				</span>
			</div>
		</div>
	);
}
```


events page AttestationItem

```
function AttestationItem({ id, data }: { id: string; data: any }) {
  const parsedData = parseEventsData(data);

  return (
    <Link
      href={`/event/${id}`}
      className="border-2 rounded-lg w-60 hover:border-slate-600"
    >
      <div className="p-3">
        <h1 className="text-base font-bold">{parsedData.name}</h1>
        <h2 className="text-xs">{parsedData.startsAt}</h2>
      </div>
      <div>
        <img
          className="w-full h-auto"
          alt="Template image"
          src={parsedData.imageUrl}
        />
      </div>
      <div className="p-3">
        <h2 className="text-xs text-gray-700 mb-4">
          Brief description: {parsedData.briefDescription}
        </h2>
        <h2 className="text-xs text-gray-700 mb-4">
          Full description: {parsedData.fullDescription}
        </h2>
      </div>
    </Link>
  );
}
```

2024-09-16 15:18 UTC, luizakp commented on src/app/page.tsx
> +			>
this is not linked to the event details page 🤔

2024-09-16 17:10 UTC, luizakp commented on src/app/page.tsx
> +		  }
startsAt can be in the past, endsAt that can't

2024-09-16 17:25 UTC, luizakp commented on src/app/page.tsx
>  function epochToCustomDate(epoch: number): string {
this already exists on events/page, no?

2024-09-19 12:20 UTC, closed without merging

2024-09-19 13:07 UTC, ribeirojose commented
when you close issues, can you post a comment just briefly explaining why they were closed? It's a bit uncanny to me to come to an issue where my review had been requested to see it closed and not know what happened 😬

2024-09-20 14:44 UTC, luizakp commented
Context: This PR was closed because it didn't deliver the task scope. A new one was created:  https://github.com/bleu/op-bacchus/pull/27